# frozen_string_literal: true

source "https://rubygems.org"

gem 'rspec',     '3.6.0'
gem 'coderay',   '1.1.1'
gem 'rack-test', '0.7.0'
gem 'sinatra',   '2.2.3'
gem 'sequel',    '4.48.0'
gem 'sqlite3',   '1.3.13'
gem 'ox'
